dist: xenial
language: python
python:
        - "3.7"
        - "3.7-dev"
        - "3.8-dev"

install:
        - python3.7 -m pip3 install -r requirements.txt

script:
        - python3.7 -m pytest src
